version: "2"
services:
  mysql:
    image: mysql:5.6.41
    restart: always
    ports:
    - "3306:3306"
    environment:
    - MYSQL_DATABASE=test
    - MYSQL_ROOT_PASSWORD=123456
    volumes:
    - ./conf:/etc/mysql/conf.d
