---
# 为外部 mysql 服务设置 service
kind: Service
apiVersion: v1
metadata:
  namespace: apollo
  name: service-mysql-for-portal-server
  labels:
    app: service-mysql-for-portal-server
spec:
  ports:
  - protocol: TCP
    port: 3306
    targetPort: 3306
  type: ClusterIP
  sessionAffinity: None
---
kind: Endpoints
apiVersion: v1
metadata:
  namespace: apollo
  name: service-mysql-for-portal-server
subsets:
- addresses:
  # 更改为你的 mysql addresses, 例如 1.1.1.1
  # 其中 1.1.1.1、2.2.2.2、3.3.3.3 为你的 mysql 集群, 例如 MySQL-Galera-WSrep 或 TiDB
  - ip: 10.10.1.120
  ports:
  - protocol: TCP
    port: 3306

---
# configmap for apollo-portal-server
kind: ConfigMap
apiVersion: v1
metadata:
  namespace: apollo
  name: configmap-apollo-portal-server
data:
  SPRING_DATASOURCE_URL: "jdbc:mysql://service-mysql-for-portal-server.apollo:3306/ApolloPortalDB?characterEncoding=utf8"
  SPRING_DATASOURCE_USERNAME: "root"
  SPRING_DATASOURCE_PASSWORD: "123456"
  DEV_META: "http://service-apollo-configservice-prod.apollo:8080"

---
kind: Service
apiVersion: v1
metadata:
  namespace: apollo
  name: service-apollo-portal-server
  labels:
    app: service-apollo-portal-server
spec:
  ports:
  - protocol: TCP
    port: 8070
    targetPort: 8070
    nodePort: 30001
  selector:
    app: pod-apollo-portal-server
  type: NodePort
  # portal session 保持
  sessionAffinity: ClientIP

---
kind: Deployment
apiVersion: apps/v1beta2
metadata:
  namespace: apollo
  name: deployment-apollo-portal-server
  labels:
    app: deployment-apollo-portal-server
spec:
  # 3 个实例
  replicas: 3
  selector:
    matchLabels:
      app: pod-apollo-portal-server
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: pod-apollo-portal-server
    spec:
      nodeSelector:
        node: "apollo"

      initContainers:
      # 确保 admin-service 正常提供服务
      - image: centos:7
        name: check-service-apollo-admin-server-prod
        command: ['bash', '-c', "curl --connect-timeout 2 --max-time 5 --retry 60 --retry-delay 1 --retry-max-time 120 service-apollo-admin-server-prod.apollo:8090"]

      containers:
      - image: registry.cn-hangzhou.aliyuncs.com/szss/apollo-portal:v1.0.0
        securityContext:
          privileged: true
        imagePullPolicy: IfNotPresent
        name: container-apollo-portal-server
        ports:
        - protocol: TCP
          containerPort: 8070

        # 挂载configmap-apollo-portal-server相关配置
        envFrom:
        - configMapRef:
            name: configmap-apollo-portal-server
        # 计算资源分配
        resources:
          # 初始请求资源
          requests:
            cpu: 0.5
            memory: 1024Mi
          # 资源限制
          limits:
            cpu: 1
            memory: 3072Mi

        readinessProbe:
          tcpSocket:
            port: 8070
          initialDelaySeconds: 10
          periodSeconds: 5

        livenessProbe:
          tcpSocket:
            port: 8070
          # 120s 内, server 未启动则重启 container
          initialDelaySeconds: 120
          periodSeconds: 15

      dnsPolicy: ClusterFirst
      restartPolicy: Always
