---
kind: Service
apiVersion: v1
metadata:
#  namespace: apollo
  name: service-mysql-for-apollo-prod
  labels:
    app: service-mysql-for-apollo-prod
spec:
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
  type: ClusterIP
  sessionAffinity: None

---
kind: Endpoints
apiVersion: v1
metadata:
#  namespace: apollo
  name: service-mysql-for-apollo-prod
subsets:
  - addresses:
      - ip: your-mysql-addresses
    ports:
      - protocol: TCP
        port: 3306